### ISSUE TITLE
Rclone config file not being detected by bot

### ISSUE THREAD

**Issue by puffious** [anasty17/mirror-leech-switch-bot#7]
Reproduce:
/usetting -> Rclone -> Rclone Config
when the prompt comes to upload config within 60 seconds
uploading config doesn't get detected and taken by bot.

Expected Behaviour:
bot should accept the config, save it and delete the rclone.conf file from messages.

Switch Version: 90.0.0
Device: Realme 3 Pro
OS: Android 12L Custom Rom

**Comment by anasty17** [comment]
Fixed
